version: '3'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      command: ["/go/bin/collector-linux", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "9411:9411"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: ["/go/bin/query-linux", "--query.static-files=/go/jaeger-ui/", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["/go/bin/agent-linux", "--collector.host-port=jaeger-collector:14267,jaeger-java-collector:2042"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector
        
    jaeger-java-collector:
      image: marioscrock/jaeger-java-collector
      command: ["java","-jar","/usr/app/jaeger-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]
      ports:
        - "2042:2042" 
      restart: on-failure
      depends_on:
        - jaeger-agent

    cassandra:
      image: cassandra:3.9

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      depends_on:
        - cassandra