version: '2'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector:1.5
      command: ["/go/bin/collector-linux", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411",
       "--collector.queue-size=300000"] #ADDED
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "9411:9411"
      restart: on-failure
      networks:
        - jaeger-net
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query:1.5
      command: ["/go/bin/query-linux", "--query.static-files=/go/jaeger-ui/", "--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      networks:
        - jaeger-net
      depends_on:
        - cassandra-schema

    # jaeger-agent:
    #   image: jaegertracing/jaeger-agent:1.5
    #   command: ["/go/bin/agent-linux", "--collector.host-port=jaeger-collector:14267"]
    #   ports:
    #     - "5775:5775/udp"
    #     - "6831:6831/udp"
    #     - "6832:6832/udp"
    #     - "5778:5778"
    #   restart: on-failure
    #   networks:
    #     - jaeger-net
    #   depends_on:
    #     - jaeger-collector

    # jaeger-agent:
    #   image: marioscrock/jaeger-agent #-debug #REMOVE DEBUG
    #   command: ["./main", "--collector.host-port=jaeger-collector:14267"]
    #   ports:
    #     - "5775:5775/udp"
    #     - "6831:6831/udp"
    #     - "6832:6832/udp"
    #     - "5778:5778"
    #   restart: on-failure
    #   networks:
    #     - jaeger-net
    #   depends_on:
    #     - jaeger-collector
    #     - kaiju-collector
        
    kaiju-collector:
     image: marioscrock/kaiju-collector
     command: ["java","-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-XX:MaxRAMFraction=1", "-jar","/usr/app/kaiju-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]
     mem_limit: 200M
     ports:
       - "2042:2042" 
       - "4567:4567"
     restart: on-failure
     networks:
       - jaeger-net

    cassandra:
      image: cassandra:3.9
      networks:
        - jaeger-net

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema:1.5
      networks:
        - jaeger-net
      depends_on:
        - cassandra

networks:
  jaeger-net:
    driver: bridge
