version: '3'

services:

  influxdb:
    image: "influxdb:latest"
    networks:
      - jaeger_jaeger-net

  telegraf:
    image: "telegraf:latest"
    networks:
      - jaeger_jaeger-net
    volumes:
      - ./etc/telegraf:/etc/telegraf
      #To enable [inputs.docker] within a container
      - /var/run/docker.sock:/var/run/docker.sock
      
  kapacitor:
    image: "kapacitor:latest"
    networks:
      - jaeger_jaeger-net
    volumes:
      - ./etc/kapacitor:/etc/kapacitor
      - ./var/log/kapacitor:/var/log/kapacitor
      - ./home/kapacitor:/home/kapacitor

networks:
  jaeger_jaeger-net:
    external: true
